---
title: "SFC"
author: "Josephine Kærsgaard"
date: "2023-04-12"
output: word_document
---
```{r}
library(sfcr)
library(tidyverse)
library(tidygraph)


#Step 1: Write the balance sheet matrix

bs_pension <- sfcr_matrix(
  columns = c("Beskæftigede", "Arbejdsløse", "Pensionister", "Production", "Government"),
  code = c("b","al","pen", "p", "g"),
  c("Money", b = "+M_b", al= "+M_al", pen="+M_pen", g = "-Ms"),
  c("Wealth", b = "-V_b", al = "-V_al", pen="-V_pen", g = "+V")
)

sfcr_matrix_display(bs_pension)
# We check the consistency of the model using the balance sheet
```


```{r}
#Step 2_ Write the TFM

tfm_pension <- sfcr_matrix(
  columns = c("Beskæftigede", "Arbejdsløse", "Pensionister", "Production", "Government"),
  codes = c("b","al", "pen", "p", "g"),
  c("Consumption", b = "-C_b", al="-C_al", pen="-C_pen", p = "+C"),
  c("Government Expenditure", p = "+G", g = "-G"),
  c("Income = GDP", b = "+Y", p = "-Y"),
  c("Interest on Loans/Public Debt", g = "-r[-1]*Ms[-1]", b = "+r[-1]*Ms[-1]"), 
  c("Pension payouts", pen = "+FP", g = "-FP"),
  c("Contributions to social security", b = "-Ss", g = "+Ss"), #ATP
  c("Unemployment benefits", al = "+DP", g = "-DP"),
  c("Tax on Income", b = "-T_b", g = "+T_b"), 
  c("Tax on Pension", pen = "-T_pen", g = "+T_pen"),
  c("Tax on Unemployment benefits", al = "-T_al", g = "+T_al"),
  c("Change in Money", b = "-(M_b - M_b[-1])", al="-(M_al - M_al[-1])", pen = "-(M_pen- M_pen[-1])", g = "(Ms - Ms[-1])")
)

sfcr_matrix_display(tfm_pension)
```


```{r}
# Write the system of equations

pension_eqs <- sfcr_set(
  #Hvordan defineres aktive og passive husholdninger som andele af hele befolkningen???
  
  #Definition af befolkning, arbejdsløse m.m
  Lf ~ beta * Pop, #arbejdsstyrken
  N ~ Y/pr, # efterspørgslen efter arbejdskraft. 
  Ul ~ Lf - N, #Det faktiske antal af arbejdsløse af den samlede arbejdsstyrke
  Pen ~ Pop - Lf, #andelen af pensionister
  
  #Regnskabsidentiteter
  Y ~ C + G,
  
  #Adfærdsliginger
  Yd_b ~ W*N + r[-1]*Ms[-1] - T_b - Ss,
  Yd_al ~ DP - T_al,
  Yd_pen ~ FP - T_pen, #Forskellige skatterater? eller skal en skattesats ganges på?
  Yd ~ Yd_b + Yd_al+ Yd_pen,
 
  FP ~ tau * W * Pen, #Folkepension. Tau ganges på lønraten for at få en sammenhæng mellem indkomst for de tre medtagne grupper. 
  Ss ~ gamma * Yd_b,
  DP ~ tau2 * W * Ul,   
 
  #Skatter
  T_b ~ theta1 * (W*N), 
  T_al ~ theta2 * DP,
  T_pen ~ theta3 * FP,
  T ~ T_b + T_al+ T_pen,
  
  #Forbrug
  C_b ~ alpha1_b * Yd_b + alpha2_b * V_b[-1],
  C_al ~ alpha1_al * Yd_al + alpha2_al * V_al[-1],
  C_pen ~ alpha1_pen * Yd_pen + alpha2_pen * V_pen[-1],
  C ~ C_b + C_al + C_pen,
  
  
  #Formue
  V_b ~ V_b[-1] + Yd_b - C_b,
  V_al ~ V_al[-1] + Yd_al - C_al,
  V_pen ~ V_pen[-1] + Yd_pen - C_pen,
  V ~ V_b + V_al + V_pen, 
  M_b ~ V_b ,
  M_al ~ V_al, 
  M_pen ~ V_pen, 
  M ~ M_b + M_al + M_pen,
  
  #Ændringer i stocks
 # Ms ~ Ms[-1] + (M - M[-1]), #skal sidste parentes med?
  Ms ~ Ms[-1]+(G+r[-1]*Ms[-1]+FP+DP)- (T+Ss)
)
```


```{r}
#sfcr_sankey(tfm_pension, pension)
# Set values for the exogenous variables and the parameters

pension_ext <- sfcr_set(
  # Exogenous
  
  r ~ 0.025,
  G ~ 10,
  theta1 ~ 0.4, 
  theta2 ~ 0.25,
  theta3 ~ 0.15,
  tau ~ 0.7, #Forbrugsudglattende. Når W og tau har samme størrelse (1). Tau er dog mindre end 1, hvorfor forbruget for pensionister ikke udglattes over livsperioden.
  tau2 ~ 0.65, #kompensationsgrad - 60%
  beta ~ 0.75, #andel af arbejdsstyrken ud af befolkningen - oprindeligt 0,75. 
  gamma ~ 0.2, #procentdel af disponibel indkomst til ss
  pr ~ 1, #Hvis produktiviteten steg, samtidigt med færre hænder, kan man risikere, at man rent faktisk kan producere mere. Her er det dog lidt det modsatte. Hvis man endogeniserer produktiviteten i modellen, vil man kunne diskutere, hvordan produktiviteten påvirkes af den demografiske udvikling.
  W ~ 1,
  Pop ~ 150, # Samlede befolkning
  
  # Parameters
  
  alpha1_b ~ 0.6,
  alpha2_b ~ 0.4,
  alpha1_al ~ 0.9,
  alpha2_al ~ 0.1,
  alpha1_pen ~ 0.9,
  alpha2_pen ~ 0.1
)

#Set initial values

pension_initial <- sfcr_set(
  M_b ~ 21.62,
  M_al ~ 0, #arbejdsløse og pensionister forbruger alt, hvorfor de ingen opsparing har.
  M_pen ~ 0,
  Ms ~ 21.62,
  V_b ~ 21.62,
  V_al ~ 0, # ingen formue, da de forbruger alt.
  V_pen ~ 0
  
  #staten printer penge for at finansiere sit underskud. 
)
```


```{r}
# Simulate the baseline model

pension <- sfcr_baseline(
  equations = pension_eqs,
  external = pension_ext,
  initial = pension_initial,
  periods = 100
)
```


```{r}
# We check the consistency of the model using the balance sheet

sfcr_validate(
  matrix = bs_pension,
  baseline = pension,
  which = "bs")

# We check the consistency of the model using the TFM

sfcr_validate(
  matrix = tfm_pension,
  baseline = pension,
  which = "tfm"
)

plot(pension$period, pension$Y, type = "l", lty = 1, main = "Baseline scenarie - BNP", xlab = "Perioder, tid", ylab= "BNP")
```


```{r}
#### SCENARIO

# Create a scenario where the interest rate increases from 0.025 to 0.035

shock <- sfcr_shock(
  variables = sfcr_set(
    beta ~ 0.65 #arbejdsstyrkens andel falder fra 0,75 til 0,65
  ),
  start = 20,
  end = 100
)

# Create the scenario where the shock takes place

pc1 <- sfcr_scenario(
  baseline = pension,
  scenario = shock,
  periods = 100
)


pension$Y
# We create the variables defining the shares of money and bills in Households portfolio.
# We use pc1 to see the impact of the change in the interest in the portfolio allocation.

pc1$MsY <- pc1$Ms/pc1$Y #her konstrueres gælden over for Y

pc1$PenPop <- pc1$Pen/pc1$Pop
pc1$PenPop

pc1 %>%
  filter(period %in% c(3, 21, 25, 50, 75, 90, 100)) %>%
  select(period, G, Y, Yd, C, Ms, MsY, PenPop) %>%
  t() %>%
  round(digits = 3)


pc1_long <- pc1 %>%
  pivot_longer(cols = -period)

#PLOTS 
pc1_long %>%
  filter(name %in% c("Y", "C")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line(aes(linetype = name)) +
  labs(title = "Ændringen i BNP og forbrug")

pc1_long %>%
  filter(name %in% c("V_b", "V_al", "V_pen")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line(aes(linetype = name)) +
  labs(title = "Ændringen i BNP og forbrug")

pc1_long %>%
  filter(name %in% c("MsY")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line() +
  facet_wrap(~ name, scales = 'free_y') +
  labs(title = "Gældsrate")


plot(pc1$period, pc1$PenPop, type="l")
plot(pc1$period, pc1$FP)

pc1_long %>%
  filter(name %in% c("PenPop")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line() +
  facet_wrap(~ name, scales = 'free_y') +
  labs(title = "Andelen af pensionister ud af populationen")

#Figure 4.4 (Remark, that it seems like Yd and C are identical
# This is not the case if you look at the table)

pc1_long %>%
  filter(name %in% c("Yd", "C")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line(aes(linetype = name)) +
  labs(title = "Evolution of disposable income and household consumption")

pc1_long %>%
  filter(name %in% c("Yd_b", "Yd_al", "Yd_pen")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line(aes(linetype = name)) +
  labs(title = "Udviklingen af disponibel indkomst")

pc1_long %>%
  filter(name %in% c("Y", "Ms")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line() +
  facet_wrap(~ name, scales = 'free_y') +
  labs(title = "Udviklingen i gælden og Y")

pc1_long %>%
  filter(name %in% c("FP", "DP")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line() +
  facet_wrap(~ name, scales = 'free_y') +
  labs(title = "Udvikling i folkepension og dagpenge")

pc1_long %>%
  filter(name %in% c("FP", "DP")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line(aes(linetype = name)) +
  labs(title = "Udviklingen i folkepension og dagpenge efter chok")


```
```{r}
shock1 <- sfcr_shock(
  variables = list(
   # beta ~ 0.65, #arbejdsstyrkens andel falder fra 0,75 til 0,65
    theta1 ~ 0.5 #
  ),
  start = 20,
  end = 100
)

# Create the scenario where the shock takes place

pc2 <- sfcr_scenario(
  baseline = pension,
  scenario = shock1,
  periods = 100
)

pc2_long <- pc2 %>%
  pivot_longer(cols = -period)

pc2_long %>%
  filter(name %in% c("Yd", "C")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line(aes(linetype = name)) +
  labs(title = "Ændringen i disponibel indkomst, forbrug og BNP")

pc2_long %>%
  filter(name %in% c("Y")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line(aes(linetype = name)) +
  labs(title = "Udviklingen i den økonomiske vækst")

pc2$MsY <- pc2$Ms/pc2$Y

pc2_long %>%
  filter(name %in% c("Ms", "MsY")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line() +
  facet_wrap(~ name, scales = 'free_y') +
  labs(title = "Gæld og Gældsrate")


pc2_long %>%
  filter(name %in% c("FP")) %>%
  ggplot(aes(x = period, y = value)) +
  geom_line() +
  facet_wrap(~ name, scales = 'free_y') +
  labs(title = "Gæld og Gældsrate")

```

